import type { CrudPageConfig } from "@/features/crud/types";

import { suppliers } from "./data";

export const suppliersConfig: CrudPageConfig = {
  title: "Suppliers / Vendors",
  description: "Manage supplier and vendor profiles for accounts payable.",
  entityName: "Supplier",
  columns: [
    { key: "name", label: "Supplier" },
    { key: "email", label: "Email" },
    { key: "phone", label: "Phone" },
    { key: "city", label: "City" },
    { key: "paymentTerms", label: "Payment Terms" },
    { key: "balance", label: "Balance", className: "text-right tabular-nums" },
    { key: "status", label: "Status" },
  ],
  fields: [
    { key: "name", label: "Supplier name", placeholder: "e.g. Horizon Supplies" },
    { key: "email", label: "Email", placeholder: "billing@example.com" },
    { key: "phone", label: "Phone", placeholder: "+1 555-0100" },
    { key: "city", label: "City", placeholder: "City" },
    {
      key: "paymentTerms",
      label: "Payment terms",
      type: "select",
      options: [
        { label: "Due on receipt", value: "Due on receipt" },
        { label: "Net 15", value: "Net 15" },
        { label: "Net 30", value: "Net 30" },
        { label: "Net 45", value: "Net 45" },
      ],
    },
    {
      key: "balance",
      label: "Opening balance",
      type: "number",
      placeholder: "0",
      required: false,
    },
    {
      key: "status",
      label: "Status",
      type: "select",
      options: [
        { label: "Active", value: "Active" },
        { label: "Inactive", value: "Inactive" },
      ],
    },
  ],
  initialRows: suppliers.map((supplier) => ({
    id: supplier.id,
    name: supplier.name,
    email: supplier.email,
    phone: supplier.phone,
    city: supplier.city,
    paymentTerms: supplier.paymentTerms,
    balance: supplier.balance,
    status: supplier.status,
  })),
};

export const supplierBillsConfig: CrudPageConfig = {
  title: "Supplier Bills",
  description: "Record and track purchase bills received from vendors.",
  entityName: "Bill",
  columns: [
    { key: "billNo", label: "Bill No" },
    { key: "supplier", label: "Supplier" },
    { key: "billDate", label: "Bill Date" },
    { key: "dueDate", label: "Due Date" },
    { key: "amount", label: "Amount", className: "text-right tabular-nums" },
    { key: "balance", label: "Balance", className: "text-right tabular-nums" },
    { key: "status", label: "Status" },
  ],
  fields: [
    { key: "billNo", label: "Bill No", placeholder: "BILL-8800" },
    {
      key: "supplier",
      label: "Supplier",
      type: "select",
      options: suppliers.map((s) => ({ label: s.name, value: s.name })),
    },
    { key: "billDate", label: "Bill date", placeholder: "YYYY-MM-DD" },
    { key: "dueDate", label: "Due date", placeholder: "YYYY-MM-DD" },
    { key: "amount", label: "Amount", type: "number", placeholder: "0" },
    {
      key: "paid",
      label: "Paid amount",
      type: "number",
      placeholder: "0",
      required: false,
    },
    {
      key: "balance",
      label: "Balance",
      type: "number",
      placeholder: "0",
      required: false,
    },
    {
      key: "status",
      label: "Status",
      type: "select",
      options: [
        { label: "Draft", value: "draft" },
        { label: "Open", value: "open" },
        { label: "Partial", value: "partial" },
        { label: "Paid", value: "paid" },
        { label: "Overdue", value: "overdue" },
      ],
    },
  ],
  initialRows: [
    {
      id: "bill1",
      billNo: "BILL-8841",
      supplier: "Horizon Supplies",
      billDate: "2026-03-01",
      dueDate: "2026-03-31",
      amount: 2450,
      paid: 0,
      balance: 2450,
      status: "open",
    },
    {
      id: "bill2",
      billNo: "BILL-8790",
      supplier: "Apex Parts",
      billDate: "2026-02-20",
      dueDate: "2026-03-07",
      amount: 3200,
      paid: 1060,
      balance: 2140,
      status: "overdue",
    },
    {
      id: "bill3",
      billNo: "BILL-8822",
      supplier: "City Utilities",
      billDate: "2026-03-10",
      dueDate: "2026-03-20",
      amount: 640,
      paid: 0,
      balance: 640,
      status: "overdue",
    },
    {
      id: "bill4",
      billNo: "BILL-8860",
      supplier: "CloudHost Inc.",
      billDate: "2026-03-15",
      dueDate: "2026-04-14",
      amount: 189,
      paid: 0,
      balance: 189,
      status: "open",
    },
  ],
};
