import type { CrudPageConfig } from "@/features/crud/types";

import { customers } from "./data";

export const customersConfig: CrudPageConfig = {
  title: "Customers",
  description: "Manage customer profiles used for receivables and invoicing.",
  entityName: "Customer",
  columns: [
    { key: "name", label: "Customer" },
    { key: "email", label: "Email" },
    { key: "phone", label: "Phone" },
    { key: "city", label: "City" },
    { key: "creditLimit", label: "Credit Limit", className: "text-right tabular-nums" },
    { key: "balance", label: "Balance", className: "text-right tabular-nums" },
    { key: "status", label: "Status" },
  ],
  fields: [
    { key: "name", label: "Customer name", placeholder: "e.g. Nova Retail" },
    { key: "email", label: "Email", placeholder: "billing@example.com" },
    { key: "phone", label: "Phone", placeholder: "+1 555-0100" },
    { key: "city", label: "City", placeholder: "City" },
    {
      key: "creditLimit",
      label: "Credit limit",
      type: "number",
      placeholder: "0",
    },
    {
      key: "balance",
      label: "Opening balance",
      type: "number",
      placeholder: "0",
      required: false,
    },
    {
      key: "status",
      label: "Status",
      type: "select",
      options: [
        { label: "Active", value: "Active" },
        { label: "Inactive", value: "Inactive" },
      ],
    },
  ],
  initialRows: customers.map((customer) => ({
    id: customer.id,
    name: customer.name,
    email: customer.email,
    phone: customer.phone,
    city: customer.city,
    creditLimit: customer.creditLimit,
    balance: customer.balance,
    status: customer.status,
  })),
};

export const customerInvoicesConfig: CrudPageConfig = {
  title: "Customer Invoices",
  description: "Create and track sales invoices issued to customers.",
  entityName: "Invoice",
  columns: [
    { key: "invoiceNo", label: "Invoice No" },
    { key: "customer", label: "Customer" },
    { key: "issueDate", label: "Issue Date" },
    { key: "dueDate", label: "Due Date" },
    { key: "amount", label: "Amount", className: "text-right tabular-nums" },
    { key: "balance", label: "Balance", className: "text-right tabular-nums" },
    { key: "status", label: "Status" },
  ],
  fields: [
    { key: "invoiceNo", label: "Invoice No", placeholder: "INV-2300" },
    {
      key: "customer",
      label: "Customer",
      type: "select",
      options: customers.map((c) => ({ label: c.name, value: c.name })),
    },
    { key: "issueDate", label: "Issue date", placeholder: "YYYY-MM-DD" },
    { key: "dueDate", label: "Due date", placeholder: "YYYY-MM-DD" },
    { key: "amount", label: "Amount", type: "number", placeholder: "0" },
    {
      key: "paid",
      label: "Paid amount",
      type: "number",
      placeholder: "0",
      required: false,
    },
    {
      key: "balance",
      label: "Balance",
      type: "number",
      placeholder: "0",
      required: false,
    },
    {
      key: "status",
      label: "Status",
      type: "select",
      options: [
        { label: "Draft", value: "draft" },
        { label: "Sent", value: "sent" },
        { label: "Partial", value: "partial" },
        { label: "Paid", value: "paid" },
        { label: "Overdue", value: "overdue" },
      ],
    },
  ],
  initialRows: [
    {
      id: "inv1",
      invoiceNo: "INV-2291",
      customer: "Nova Retail",
      issueDate: "2026-03-01",
      dueDate: "2026-03-31",
      amount: 8500,
      paid: 0,
      balance: 8500,
      status: "sent",
    },
    {
      id: "inv2",
      invoiceNo: "INV-2288",
      customer: "Bright Media Ltd.",
      issueDate: "2026-02-10",
      dueDate: "2026-03-12",
      amount: 3800,
      paid: 0,
      balance: 3800,
      status: "overdue",
    },
    {
      id: "inv3",
      invoiceNo: "INV-2275",
      customer: "Summit Contractors",
      issueDate: "2026-01-20",
      dueDate: "2026-02-19",
      amount: 12000,
      paid: 2800,
      balance: 9200,
      status: "overdue",
    },
    {
      id: "inv4",
      invoiceNo: "INV-2301",
      customer: "Orion Logistics",
      issueDate: "2026-03-15",
      dueDate: "2026-04-14",
      amount: 920,
      paid: 0,
      balance: 920,
      status: "sent",
    },
  ],
};
