import type { CrudPageConfig } from "@/features/crud/types";

import { customers } from "./data";

export const customersConfig: CrudPageConfig = {
  title: "Customers",
  description: "Manage customer profiles used for receivables and invoicing.",
  entityName: "Customer",
  columns: [
    { key: "customer_code", label: "Code" },
    { key: "customer_name", label: "Customer" },
    { key: "customer_type", label: "Type" },
    { key: "contact_person", label: "Contact" },
    { key: "mobile_no", label: "Mobile" },
    { key: "email", label: "Email" },
    { key: "status", label: "Status" },
  ],
  fields: [
    {
      key: "customer_name",
      label: "Customer name",
      placeholder: "e.g. Nova Retail",
    },
    {
      key: "customer_type",
      label: "Customer type",
      type: "select",
      required: false,
      options: [
        { label: "Individual", value: "Individual" },
        { label: "Business", value: "Business" },
        { label: "Government", value: "Government" },
        { label: "NGO", value: "NGO" },
        { label: "Other", value: "Other" },
      ],
    },
    {
      key: "contact_person",
      label: "Contact person",
      placeholder: "e.g. Jane Doe",
      required: false,
    },
    {
      key: "designation",
      label: "Designation",
      placeholder: "e.g. Accounts Manager",
      required: false,
    },
    {
      key: "phone",
      label: "Phone",
      placeholder: "+1 555-0100",
      required: false,
    },
    {
      key: "mobile_no",
      label: "Mobile",
      placeholder: "+1 555-0101",
      required: false,
    },
    {
      key: "email",
      label: "Email",
      placeholder: "billing@example.com",
      required: false,
    },
    {
      key: "address",
      label: "Address",
      type: "textarea",
      placeholder: "Street, city, country",
      required: false,
    },
    {
      key: "status",
      label: "Status",
      type: "select",
      options: [
        { label: "Active", value: "active" },
        { label: "Inactive", value: "inactive" },
      ],
    },
  ],
  initialRows: [],
};

export const customerInvoicesConfig: CrudPageConfig = {
  title: "Customer Invoices",
  description: "Create and track sales invoices issued to customers.",
  entityName: "Invoice",
  columns: [
    { key: "invoiceNo", label: "Invoice No" },
    { key: "customer", label: "Customer" },
    { key: "issueDate", label: "Issue Date" },
    { key: "dueDate", label: "Due Date" },
    { key: "amount", label: "Amount", className: "text-right tabular-nums" },
    { key: "balance", label: "Balance", className: "text-right tabular-nums" },
    { key: "status", label: "Status" },
  ],
  fields: [
    { key: "invoiceNo", label: "Invoice No", placeholder: "INV-2300" },
    {
      key: "customer",
      label: "Customer",
      type: "select",
      options: customers.map((c) => ({ label: c.name, value: c.name })),
    },
    { key: "issueDate", label: "Issue date", placeholder: "YYYY-MM-DD" },
    { key: "dueDate", label: "Due date", placeholder: "YYYY-MM-DD" },
    { key: "amount", label: "Amount", type: "number", placeholder: "0" },
    {
      key: "paid",
      label: "Paid amount",
      type: "number",
      placeholder: "0",
      required: false,
    },
    {
      key: "balance",
      label: "Balance",
      type: "number",
      placeholder: "0",
      required: false,
    },
    {
      key: "status",
      label: "Status",
      type: "select",
      options: [
        { label: "Draft", value: "draft" },
        { label: "Sent", value: "sent" },
        { label: "Partial", value: "partial" },
        { label: "Paid", value: "paid" },
        { label: "Overdue", value: "overdue" },
      ],
    },
  ],
  initialRows: [
    {
      id: "inv1",
      invoiceNo: "INV-2291",
      customer: "Nova Retail",
      issueDate: "2026-03-01",
      dueDate: "2026-03-31",
      amount: 8500,
      paid: 0,
      balance: 8500,
      status: "sent",
    },
    {
      id: "inv2",
      invoiceNo: "INV-2288",
      customer: "Bright Media Ltd.",
      issueDate: "2026-02-10",
      dueDate: "2026-03-12",
      amount: 3800,
      paid: 0,
      balance: 3800,
      status: "overdue",
    },
    {
      id: "inv3",
      invoiceNo: "INV-2275",
      customer: "Summit Contractors",
      issueDate: "2026-01-20",
      dueDate: "2026-02-19",
      amount: 12000,
      paid: 2800,
      balance: 9200,
      status: "overdue",
    },
    {
      id: "inv4",
      invoiceNo: "INV-2301",
      customer: "Orion Logistics",
      issueDate: "2026-03-15",
      dueDate: "2026-04-14",
      amount: 920,
      paid: 0,
      balance: 920,
      status: "sent",
    },
  ],
};
